<?xml version="1.0" encoding="utf-8"?><Database Name="PostcardDatabase" Class="PostcardsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\PostcardDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PostcardDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Postcard" Member="Postcard">
    <Type Name="Postcard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhotoPlaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SenderPlaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageLink" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="CardId" Type="System.String" DbType="NVARCHAR(10)" CanBeNull="true" />
      <Association Name="Place_Postcard" Member="Place" ThisKey="PhotoPlaceId" OtherKey="Id" Type="Place" IsForeignKey="true" />
      <Association Name="Place_Postcard1" Member="Place1" ThisKey="SenderPlaceId" OtherKey="Id" Type="Place" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Place" Member="Place">
    <Type Name="Place">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsDomestic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lon" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Lat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Place_Postcard" Member="Postcard" ThisKey="Id" OtherKey="PhotoPlaceId" Type="Postcard" />
      <Association Name="Place_Postcard1" Member="Postcard1" ThisKey="Id" OtherKey="SenderPlaceId" Type="Postcard" />
    </Type>
  </Table>
</Database>